name: CI
on: [push, pull_request]

jobs:
  tests:
    name: Unit tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --color always
      - run: cargo run -- --help
  lint:
    name: Rustfmt and Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy, rustfmt
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --color always --tests -- -D warnings
      - run: rustup component add rustfmt
      - name: rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check --color always
  docker:
    name: Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        id: image
        uses: docker/build-push-action@v2
        with:
          push: false
      - name: Test Docker image
        run: |
          want="https://github.com/rhysd/vim-crystal"
          have="$(echo "https://github.com/rhysd/vim-crystal" | docker run -i --rm ${{ steps.image.outputs.digest }})"
          if [[ "$have" != "$want" ]]; then
            echo "expected ${want} but got ${have}" >&2
            exit 1
          fi
      - name: Lint Dockerfile with hadolint
        run: docker run --rm -i hadolint/hadolint hadolint --ignore DL3007 --ignore DL3008 --strict-labels - < Dockerfile
