name: Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get tag name
        id: tag
        run: |
          echo "::set-output name=name::${GITHUB_REF#refs/tags/v}"
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: rhysd
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            rhysd/fixred:${{ steps.tag.outputs.name }}
            rhysd/fixred:latest
